spring.application.name=springboot29


# URL de conexión (cambia 'mibasededatos' por el nombre real de tu BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/productos

# Credenciales de tu servidor PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=12345

# Driver explícito (buena práctica)
spring.datasource.driver-class-name=org.postgresql.Driver

# Opcional: Configuración para ver el SQL en la consola y gestionar tablas
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
