spring.application.name=jpaprueba
# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
# URL de conexión (cambia "tu_base_de_datos" por el nombre real de tu BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/jpaPrueba

# Credenciales de acceso
spring.datasource.username=postgres
spring.datasource.password=12345

# Driver de conexión
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Muestra en la consola las consultas SQL que hace Java (muy útil para depurar)
spring.jpa.show-sql=true

# Actualiza la estructura de la base de datos automáticamente sin borrar tus datos
spring.jpa.hibernate.ddl-auto=update

# Indica el dialecto específico de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect